pacing_sec = 1
oracledbPath = r"C:\Program Files\instantclient-basic-windows.x64-21.10.0.0.0dbru\instantclient_21_10"
ip = '192.168.'
port = '9999'
service_name = 'name'
user = 'user'
pswrd = ' pswrd '
JMS_HEADER_TYPE = "SYS.AQ$_JMS_HEADER"
JMS_PROPS_TYPE = "SYS.AQ$_JMS_USERPROPARRAY"
JMS_PROPERTY = "SYS.AQ$_JMS_USERPROPERTY"
MSG_TYPE = 'SYS.AQ$_JMS_BYTES_MESSAGE'
queue_name = "Q_NAME"